services:
  web:
    container_name: web
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
